name: reservation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_firestorage: ^0.2.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.6
  datetime_picker_formfield: ^2.0.1
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_datetime_picker: ^1.5.1
  flutter_image_compress: ^2.1.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  kartal: ^3.5.0
  linear_step_indicator: ^1.0.0+3
  lottie: ^3.0.0
  page_transition: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  uuid: ^4.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/defaults/
    - assets/svgs/
    - assets/icons/bottom_navbar/
    - assets/lotties/
