// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrrLEnY0lvQiGPK6Mo7YpegU5ZdcSGuKo',
    appId: '1:471449997339:web:71b819518dd214fdcea8be',
    messagingSenderId: '471449997339',
    projectId: 'tst-reservation',
    authDomain: 'tst-reservation.firebaseapp.com',
    storageBucket: 'tst-reservation.appspot.com',
    measurementId: 'G-B2XLVS4RP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7-yJR50Rmfm4ElEnI-wjiFZHSOKYi4M',
    appId: '1:471449997339:android:96b18b3c290a71ebcea8be',
    messagingSenderId: '471449997339',
    projectId: 'tst-reservation',
    storageBucket: 'tst-reservation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJR4xMtw72nDaVtDN4E1zVL6jQkGs0_o',
    appId: '1:471449997339:ios:4b65bf3e39e40b7acea8be',
    messagingSenderId: '471449997339',
    projectId: 'tst-reservation',
    storageBucket: 'tst-reservation.appspot.com',
    iosClientId: '471449997339-p9sv0o6p9lhk6qkg6q1r368vbvg2tddv.apps.googleusercontent.com',
    iosBundleId: 'link.ignotus.example.reservation',
  );
}
